### ISSUE TITLE
Command line functionality failure

### ISSUE THREAD

**Issue by gabemorris12** [SubhashUFlorida/millipede-bar#4]
I believe there is an issue when attempting to write the analytical output from the command line. Here is an example:

```
python millipede_bar.py --incident data/gaussian_T1.csv --parameters parameters.toml --write
```

**Output**
```
(venv) C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork>python millipede_bar.py --incident data/gaussian_T1.csv --parameters parameters.toml --write
Traceback (most recent call last):
  File "C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork\millipede_bar.py", line 142, in <module>
    main()
  File "C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork\venv\lib\site-packages\click\core.py", line 1055, in main    
    rv = self.invoke(ctx)
  File "C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork\venv\lib\site-packages\click\core.py", line 1404, in invoke  
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork\venv\lib\site-packages\click\core.py", line 760, in invoke   
    return __callback(*args, **kwargs)
  File "C:\Users\gmbra\Downloads\CAVS\Millipede Bar Fork\millipede_bar.py", line 133, in main
    filename = incident.stem
AttributeError: 'str' object has no attribute 'stem'
```

It appears that y'all's intent is that `incident` needs to be a path object, but it is instead the untouched string that the user passes in. Inserting `incident = Path(incident)` above line 132 appears to fix this.

**Comment by salil91** [comment]
That makes sense. I changed `incident` to be a Path object in line 35, but forgot to do so at line 135. Thanks for catching this.
